### ISSUE TITLE
error

### ISSUE THREAD

**Issue by dezhob** [Qengineering/TensorFlow_Lite_Face_Mask_Jetson-Nano#2]
hi, the script runs with an error 
**Cannot find -ltensorflow-lite: No such file or directory
error: ld returned 1 exit status**

**Comment by dezhob** [comment]
I run the script with rpi5 
tensorflow was installed using this instruction https://qengineering.eu/install-tensorflow-2-lite-on-raspberry-64-os.html

**Comment by Qengineering** [comment]
Do you have `libtensorflow-lite.a`, as shown in the instructions?
Was he installation of TF-Lite a success?
You need to place all required libs in /usr/local/lib, as you know.

**Comment by dezhob** [comment]
thx<3
